### PR TITLE
Parse data when chunk ends with CRLF

### PR DESCRIPTION
**Pull request by josacar**
Solves #18

---
This change is [Reviewable](https://reviewable.io/reviews/nukeproof/oanda_api/22)

### CODE REVIEW

**Comment by josacar** [comment]
I have not any issue in hours, so looks like it's solid. Have to check memory usage over the time.

**Comment by josacar** [comment]
I started with this approach, but this makes a lot of tests crash, as it's processing every chunk one by one as `handle_response` only receives one chunk at a time.

Also I'm experiencing some freezes with the `IO.pipe` approach after some minutes, maybe using `Fiber` is needed as `IO#gets` blocks until there's data in the pipe to load.

```ruby
def stream(&block)
  @stop_requested = false
  @running = true
  # @http.set_debug_output $stderr
  r, w = IO.pipe
  @http.request(@request) do |response|
    response.read_body do |chunk|
      w << chunk

      handle_response(r.gets("\r\n")).each do |resource|
        block.call(resource, @client)
        return if stop_requested?
      end

      return if stop_requested?
      sleep 0.01
    end
  end
ensure
  @running = false
  @http.finish if @http.started?
end
```

**Comment by nukeproof** [comment]
I'm surprised that it would block because I was thinking that every chunk yielded by #read_body would contain at least one complete serialized JSON object, which should be terminated by CRLF?

**Comment by josacar** [comment]
The problem is they are sharing the same thread, but they should use different `Fiber`.

Taking the approach with `Thread` I have no freeze:

```ruby
def stream(&block)
  @stop_requested = false
  @running = true
  # @http.set_debug_output $stderr
  r, w = IO.pipe
  Thread.new do
    loop do
      handle_response(r.gets("\r\n")).each do |resource|
        block.call(resource, @client)
        return if stop_requested?
      end

      return if stop_requested?
      sleep 0.01
    end
  end

  @http.request(@request) do |response|
    response.read_body do |chunk|
      w << chunk
    end
  end
ensure
  @running = false
  @http.finish if @http.started?
end
```

**Comment by josacar** [comment]
I think the latter is a bigger change as it involves bigger changes. Also current master is broken as `IO#flush` doesn't clear the buffer, so it gets appended over and over, so `IO#truncate` and `IO#rewind` is needed to really clear it.

**Comment by nukeproof** [comment]
I think the threaded approach is too complicated.  And it turns out that there's also no real benefit to using the IO.pipe approach either, so I think going back to your original suggestion using the regex: 
`next unless chunk.match(/\r\n\Z/)` was the best solution.

**Comment by joseluis-fw** [comment]
@nukeproof anything missing in this PR then?

**Pull request closed without merging**
